### ISSUE TITLE
Parsing individual title

### ISSUE THREAD

**Issue by michelesalvador** [FamilySearch/gedcom5-java#11]
Take a GEDCOM with this individual:
```
0 @I1@ INDI
1 NAME Victoria /Hanover/
1 TITL Queen of England
```
[`ModelParser.handleTitl(Object)`](https://github.com/FamilySearch/Gedcom/blob/bf091ee265b411662e0c380810d4d5ada25033b4/src/main/java/org/folg/gedcom/parser/ModelParser.java#L1376) puts the `TITL` record within `names` adding the user-defined `_type` key:
```
{
  "id": "I1",
  "names": [
    {
      "value": "Victoria /Hanover/"
    },
    {
      "_type": "TITL",
      "value": "Queen of England"
    }
  ]
}
```
This is strange, because in [GEDCOM 5.5](http://user.it.uu.se/~andersa/gedcom/ch2.html#SINDIVIDUAL) specifications `TITL` is a standard attribute of `INDI` (like for example `OCCU` or `PROP`):
```
INDIVIDUAL:=
n  <<NAME_STRUCTURE>>		{1:M}
n  TITL <INDI_TITLE>		{0:M}
n  ...
```
And also in [GEDCOM 5.5.1](http://phpgedview.sourceforge.net/ged551-5.pdf) `TITL` is located among other standard attributes:
```
INDIVIDUAL_ATTRIBUTE_STRUCTURE:=
  [
  n ...
  |
  n TITL <NOBILITY_TYPE_TITLE>		{1:1}
    +1 <<INDIVIDUAL_EVENT_DETAIL>>	{0:1}
  ]
```
Wouldn't be more correct to parse the `TITL` record as a simple `EventFact`? Like this:
```
{
  "id": "I1",
  "names": [
    {
      "value": "Victoria /Hanover/"
    }
  ]
  "eventsFacts": [
    {
      "tag": "TITL",
      "value": "Queen of England"
    }
  ]
}
```

**Comment by stoicflame** [comment]
Fair enough. I'm happy to merge a pull request.
