### ISSUE TITLE
Support InputStream and Reader parse on all parsers

### ISSUE THREAD

**Issue by jbonevich** [FamilySearch/gedcom5-java#16]
I am working with GEDCOMs stored as S3 objects, and I want to work with content as streams or readers (i.e. S3.getObject().getObjectContent()).  It would be nice to have GedcomParser.parse(InputStream) or parse(Reader), and corresponding methods on ModelParser, TreeParser, and JsonParser.

**Comment by stoicflame** [comment]
Agreed.

Want to put together a pull request for us?

**Comment by jbonevich** [comment]
I can absolutely do that.

**Comment by stoicflame** [comment]
Version 1.11.0 has been released.
