### ISSUE TITLE
Hosting this JAR on Maven Central

### ISSUE THREAD

**Issue by Sternbach-Software** [FamilySearch/gedcom5-java#34]
It would be nice if I could import this jar from Maven Central or MVN Repository, without having to manually build every update, as well as being able to keep tabs on the newest version. It would also be nice to have the sources by default. 
 @michelesalvador's FamilyGem app has a source-less local JAR.

**Comment by stoicflame** [comment]
Latest HEAD has been cut as `1.14.0` in Maven Central. 

We're happy to cut and publish new versions as updates are merged.

**Comment by Sternbach-Software** [comment]
Can you provide a link or a gradle `implementation`/maven `dependency`? And mention that in the readme?
