### ISSUE TITLE
getSubmitters() can return null

### ISSUE THREAD

**Issue by michelesalvador** [FamilySearch/gedcom5-java#4]
I tried version 1.9.0 and I encountered one problem.
With this version it's possible to parse a Json file only if it contains a `subms` key. Therefore Json files created with version 1.8.0 can no longer be opened because they don't have a `subms` key.
This is due to `Gedcom.createIndexes()` that calls `Gedcom.getSubmitters()` that can return a null `subms` object.
The same happens parsing a GEDCOM file: `Gedcom.createIndexes()` works only if the GEDCOM contains at least one `SUBM` tag.

**Comment by stoicflame** [comment]
Thanks for the report. Do you want to put together a pull request with the fix?

**Comment by michelesalvador** [comment]
Yes I will do that.
