### ISSUE TITLE
Overcome Gedcom.getSubmitter()

### ISSUE THREAD

**Issue by michelesalvador** [FamilySearch/gedcom5-java#9]
[`Gedcom.getSubmitter()`](https://github.com/FamilySearch/Gedcom/blob/bf091ee265b411662e0c380810d4d5ada25033b4/src/main/java/org/folg/gedcom/model/Gedcom.java#L188) always returns the first submitter, and has [now](https://github.com/FamilySearch/Gedcom/releases/tag/1.10.0) been replaced by `Header.getSubmitter(Gedcom)`, that returns the correct submitter, which is not necessarily the first one.

I think there is still something to do about the task of [multiple submitters](https://github.com/FamilySearch/Gedcom/issues/2):
- [x] Method `Gedcom.getSubmitter()` should be removed, or at least deprecated.
- [x] In `Header` there are a couple of comments recommending to use `Gedcom.getSubmitter`, and they should be removed.

**Comment by stoicflame** [comment]
Fair enough. I'm happy to merge a pull request.
